schema = 3

[mod]
  [mod."github.com/99designs/gqlgen"]
    version = "v0.17.2"
    hash = "sha256-bO4BtFEG4DZIAqCqZuPCBW1SIEO3w1O5OTtiU0eYVMk="
  [mod."github.com/Yamashou/gqlgenc"]
    version = "v0.0.6"
    hash = "sha256-wwYrXqFB675XPSunnMKoSNg9RF6q19YLUY4PVDEmf74="
  [mod."github.com/agnivade/levenshtein"]
    version = "v1.1.1"
    hash = "sha256-tgv2s8XIcWjscv1pP87TOIUV4vADT2px1Lo/MQCTBjM="
  [mod."github.com/anacrolix/dms"]
    version = "v1.2.2"
    hash = "sha256-UdlhZy0Qdtt0abXlF8mF9WjbJfwhkJtiyzUImIaueLA="
  [mod."github.com/antchfx/htmlquery"]
    version = "v1.2.5-0.20211125074323-810ee8082758"
    hash = "sha256-wJUs5xvusSghLrIr17mIOYG/SY97ugb+pDC0f14x+A4="
  [mod."github.com/antchfx/xpath"]
    version = "v1.2.0"
    hash = "sha256-CDyKUtBj6s65LqdCJeDv6k1dxIsE1GGRw0ohItTsLeI="
  [mod."github.com/asticode/go-astikit"]
    version = "v0.20.0"
    hash = "sha256-WL7FQlnmpEgq4gtMQ9XL0LbESBuXJ3zYggMidDS3BAw="
  [mod."github.com/asticode/go-astisub"]
    version = "v0.20.0"
    hash = "sha256-Zlwgj57x/1qEByT5SITBgin5hWxWq8fCR7Jg9ZndL5w="
  [mod."github.com/asticode/go-astits"]
    version = "v1.8.0"
    hash = "sha256-nfddti3I5Zg9K9vUWFZq+OhzgKhEB/VVUlA+lhhmzvA="
  [mod."github.com/chromedp/cdproto"]
    version = "v0.0.0-20210622022015-fe1827b46b84"
    hash = "sha256-Z2RFCfyPm503+cAoT2tMjt0dqovaisnhSWMce2fiH0c="
  [mod."github.com/chromedp/chromedp"]
    version = "v0.7.3"
    hash = "sha256-mpw5P5utGvJ65mgxpbYVARTyiKtvZwQA3bD0/6ZE3+A="
  [mod."github.com/chromedp/sysutil"]
    version = "v1.0.0"
    hash = "sha256-q0D6shGNtlM1EDiSXiysOSj+GKXerywCDHy6bV+Hn20="
  [mod."github.com/corona10/goimagehash"]
    version = "v1.0.3"
    hash = "sha256-YUI5+W/bbkEs16OA/gTb9Ez89ocg+Z2el3wVM1kV2Zs="
  [mod."github.com/cpuguy83/go-md2man/v2"]
    version = "v2.0.1"
    hash = "sha256-R+8iYit0mZjCxiGlp2C3Y5tGhySSNFU1v6wqsWKGBPM="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/disintegration/imaging"]
    version = "v1.6.0"
    hash = "sha256-XSRI+ugFeEAmdiDv5CnsyKpQlzfVMeiQKHqAYT7JQqs="
  [mod."github.com/doug-martin/goqu/v9"]
    version = "v9.18.0"
    hash = "sha256-WiRw+2W8eRKfXrifu48mvLAXcQ1XjELWkYeFpzVGWxo="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.5.1"
    hash = "sha256-B8kZ8yiWgallT7R2j1kSRJcJkSGFVf9ise+TpXa+7XY="
  [mod."github.com/fvbommel/sortorder"]
    version = "v1.0.2"
    hash = "sha256-4GXrXQ7yqTE5lSuSLBLrUH8gka9BrkDM2uZSf9W8agw="
  [mod."github.com/go-chi/chi"]
    version = "v4.0.2+incompatible"
    hash = "sha256-iPBX33fAci7W9O0MZJkcTLb4jBNDulMv3uk6uMO+txo="
  [mod."github.com/go-chi/chi/v5"]
    version = "v5.0.0"
    hash = "sha256-/XHvPEvk0zFxPeybu4GT3gQyf5R6p9JjOSF6RHPVTak="
  [mod."github.com/go-chi/httplog"]
    version = "v0.2.1"
    hash = "sha256-uS9SSBjldEgmf7NUdcVckvZ9sFZkr+U1eqprwdIPvSo="
  [mod."github.com/go-toast/toast"]
    version = "v0.0.0-20190211030409-01e6764cf0a4"
    hash = "sha256-A2CcALnNGu+5xk3qWaIyKBUzGuJXcw1iIUOQZnCzInA="
  [mod."github.com/gobwas/httphead"]
    version = "v0.1.0"
    hash = "sha256-6wFni/JkK2GqtVs3IW+GxHRNoSu4EJfzaBRGX2hF1IA="
  [mod."github.com/gobwas/pool"]
    version = "v0.2.1"
    hash = "sha256-py8/+Wo5Q83EbYMUKK5U/4scRcyMo2MjOoxqi5y+sUY="
  [mod."github.com/gobwas/ws"]
    version = "v1.1.0-rc.5"
    hash = "sha256-eizimBqOEAIU1xblVgydn9r7wQ5v/8vljwkky2+udcg="
  [mod."github.com/golang-jwt/jwt/v4"]
    version = "v4.0.0"
    hash = "sha256-m/Enz2eiBx6tht0G04UV5tyiFyu6q1fTG5h5NbYQgW0="
  [mod."github.com/golang-migrate/migrate/v4"]
    version = "v4.15.0-beta.1"
    hash = "sha256-LVvrGzjGcpFAcCdAephxKROKpT/HXGjcCq6x/7SAAkQ="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20210331224755-41bb18bfe9da"
    hash = "sha256-7Gs7CS9gEYZkbu5P4hqPGBpeGZWC64VDwraSKFF+VR0="
  [mod."github.com/gorilla/securecookie"]
    version = "v1.1.1"
    hash = "sha256-IBBYWfdOuXvQsb01DaA8tBizCfAE1J2KLXIn3W+NeJk="
  [mod."github.com/gorilla/sessions"]
    version = "v1.2.0"
    hash = "sha256-4V7yd/vf03CEsb3pz5dbLWwv7t9QgKkEhVXtc1/z5s8="
  [mod."github.com/gorilla/websocket"]
    version = "v1.4.2"
    hash = "sha256-GhBLM/XTm2lFCyDvJbnCLAI2OyYXQV6W+jRPOQ1PdVY="
  [mod."github.com/hashicorp/errwrap"]
    version = "v1.0.0"
    hash = "sha256-LGSLrefkABG1kH1i+GUWiD2/ggJxiZEJ+D2YNbhZjmo="
  [mod."github.com/hashicorp/go-multierror"]
    version = "v1.1.0"
    hash = "sha256-c0zgZsrOoA1+j7N7uIU0ZAUAa7mM8t9nfJgele+/sl4="
  [mod."github.com/hashicorp/golang-lru"]
    version = "v0.5.4"
    hash = "sha256-1skUMZX+iIf66J1TBVYGWO1OWwQcaoXut3mne331q+k="
  [mod."github.com/hashicorp/hcl"]
    version = "v1.0.0"
    hash = "sha256-xsRCmYyBfglMxeWUvTZqkaRLSW+V2FvNodEDjTGg1WA="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.0.0"
    hash = "sha256-ogTuLrV40FwS4ueo4hh6hi1wPywOI+LyIqfNjsibwNY="
  [mod."github.com/jinzhu/copier"]
    version = "v0.0.0-20190924061706-b57f9002281a"
    hash = "sha256-o4B8hw2Rqdhn134ejXJogchOrWJlxL8MeI1GTY3ZLiA="
  [mod."github.com/jmoiron/sqlx"]
    version = "v1.3.1"
    hash = "sha256-qRiJ11jKwXSQxl7M41LvqMUlGe87ktd5jzrSVFjIvuk="
  [mod."github.com/josharian/intern"]
    version = "v1.0.0"
    hash = "sha256-LJR0QE2vOQ2/2shBbO5Yl8cVPq+NFrE3ers0vu9FRP0="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.12"
    hash = "sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM="
  [mod."github.com/kermieisinthehouse/gosx-notifier"]
    version = "v0.1.1"
    hash = "sha256-HjbZhsmk+Xx7FG1ZM2TDqI1lodan21ty9codr+T5jfQ="
  [mod."github.com/kermieisinthehouse/systray"]
    version = "v1.2.4"
    hash = "sha256-ychz6BoueXnoQQjb/IZXYOGIcqTpdhnGw38GYb/UwJg="
  [mod."github.com/lucasb-eyer/go-colorful"]
    version = "v1.2.0"
    hash = "sha256-Gg9dDJFCTaHrKHRR1SrJgZ8fWieJkybljybkI9x0gyE="
  [mod."github.com/magiconair/properties"]
    version = "v1.8.6"
    hash = "sha256-xToSfpuePctkTdhJtsuKIEkXwfMZbnkFT98ahIfd4wY="
  [mod."github.com/mailru/easyjson"]
    version = "v0.7.7"
    hash = "sha256-NVCz8MURpxgOjHXqxOZExqV4bnpHggpeAOyZDArjcy4="
  [mod."github.com/matryer/moq"]
    version = "v0.2.6"
    hash = "sha256-V1Y4bWnifvMG9dBoRqw0aKx20bBfqxRVofUs8osd6Us="
  [mod."github.com/mattn/go-sqlite3"]
    version = "v1.14.7"
    hash = "sha256-JXoVZr5N7TMFk8SLppmhKpwlWVApfiayyd750o+mRBk="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.1.0"
    hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.4.3"
    hash = "sha256-2tuF/RgrEBKPYdfwTxvXATbylAlRkOxvUXNTXNo/NzM="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.2"
    hash = "sha256-+W9EIW7okXIXjWEgOaMh58eLvBZ7OshW2EhaIpNLSBU="
  [mod."github.com/natefinch/pie"]
    version = "v0.0.0-20170715172608-9a0d72014007"
    hash = "sha256-v7H7UmusN/WJwq5/DzfNK169zKFsDwGp9UhZ9leTN+4="
  [mod."github.com/nfnt/resize"]
    version = "v0.0.0-20180221191011-83c6a9932646"
    hash = "sha256-yvPV+HlDOyJsiwAcVHQkmtw8DHSXyw+cXHkigXm8rAA="
  [mod."github.com/nu7hatch/gouuid"]
    version = "v0.0.0-20131221200532-179d4d0c4d8d"
    hash = "sha256-kjtBbQTeMAMtNAA/W35XuOtr7VCwBDW8EZUHXnp0Xsc="
  [mod."github.com/pelletier/go-toml"]
    version = "v1.9.4"
    hash = "sha256-R9u+VxearUE1fLLTcAoHTrV8ZhgE/KxXRNClmrfTLn0="
  [mod."github.com/pkg/browser"]
    version = "v0.0.0-20210911075715-681adbf594b8"
    hash = "sha256-JZhcXaILA6QFOYnVdiHbKQuKABQNAE0VhMWZXsZngLQ="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/remeh/sizedwaitgroup"]
    version = "v1.0.0"
    hash = "sha256-CtjNoNeep0TnfkuRN/rc48diAo0jUog1fOz3I/z6jfc="
  [mod."github.com/robertkrimen/otto"]
    version = "v0.0.0-20200922221731-ef014fd054ac"
    hash = "sha256-bFbzS9/NLBpF5HySSyw8i3MApIId6BZY9MJu03FwXtQ="
  [mod."github.com/rs/cors"]
    version = "v1.6.0"
    hash = "sha256-uZGkVBiG99mmNHfiSJK9sw02f4K2Bo178Il2IzMaSIo="
  [mod."github.com/rs/zerolog"]
    version = "v1.26.1"
    hash = "sha256-BGCCAcaAyw0Cvlc2JwmNWwri0+Y/jwJIgqjYrdTi7gg="
  [mod."github.com/russross/blackfriday/v2"]
    version = "v2.1.0"
    hash = "sha256-R+84l1si8az5yDqd5CYcFrTyNZ1eSYlpXKq6nFt4OTQ="
  [mod."github.com/shurcooL/graphql"]
    version = "v0.0.0-20181231061246-d48a9a75455f"
    hash = "sha256-QOzqUqItT3GnjIddOjIjpLI8/LcnctMMvDl3pM500hI="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.8.1"
    hash = "sha256-vUIDlLXYBD74+JqdoSx+W3J6r5cOk63heo0ElsHizoM="
  [mod."github.com/spf13/afero"]
    version = "v1.8.2"
    hash = "sha256-ERuG4GK1LOn72DRbT9URpo1QoVIm2A3mPtlf+xSPgx8="
  [mod."github.com/spf13/cast"]
    version = "v1.4.1"
    hash = "sha256-jaY+/RKUviKnE2h8Ly5cdZYinSE0uc32FW6+xfZ1Ghs="
  [mod."github.com/spf13/cobra"]
    version = "v1.4.0"
    hash = "sha256-I6j9sD61Ztcc2W/WGeWo3ggYtnGTxNxZ2EFPdtO0UEY="
  [mod."github.com/spf13/jwalterweatherman"]
    version = "v1.1.0"
    hash = "sha256-62BQtqTLF/eVrTOr7pUXE7AiHRjOVC8jQs3/Ehmflfs="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/spf13/viper"]
    version = "v1.10.1"
    hash = "sha256-DHPdnR8nFkHFYcfNkPkk4xLuOM1GhSu1xT48umvWab4="
  [mod."github.com/stretchr/objx"]
    version = "v0.2.0"
    hash = "sha256-fx9mfz6FjbV2YtLQzk7Wzd+saejwoad2scLLC7Apvnw="
  [mod."github.com/stretchr/testify"]
    version = "v1.7.0"
    hash = "sha256-t1I9uCrn9vSUu/z5IZuNyGShmbOcJ6UGc2f75ZBrHzE="
  [mod."github.com/subosito/gotenv"]
    version = "v1.2.0"
    hash = "sha256-RUsfBl9xvHk8H6SPwiLi/BpHjkyO/YLvlFmRfGRIW1U="
  [mod."github.com/tidwall/gjson"]
    version = "v1.9.3"
    hash = "sha256-EUaWUTATM2UrGZKyYvKkmU9bEPmfMIRmZ84Nc3nJgh0="
  [mod."github.com/tidwall/match"]
    version = "v1.1.1"
    hash = "sha256-M2klhPId3Q3T3VGkSbOkYl/2nLHnsG+yMbXkPkyrRdg="
  [mod."github.com/tidwall/pretty"]
    version = "v1.2.0"
    hash = "sha256-esRQGsn2Ee/CiySlwyuOICSLdqUkH4P7u8qXszos8Yc="
  [mod."github.com/urfave/cli/v2"]
    version = "v2.4.0"
    hash = "sha256-TMdUb94NPbDF5g59qLAsvi/bJTnC0e6kRfA0O+yg5Og="
  [mod."github.com/vearutop/statigz"]
    version = "v1.1.6"
    hash = "sha256-kC0CpwlQOFZw0dEqt3nG46C+MkKqGCOekdq20Ch6RIQ="
  [mod."github.com/vektah/dataloaden"]
    version = "v0.3.0"
    hash = "sha256-PPL+mG5m4Z3dIdRNBOiDHuUACGx25bLq6Ql7SciHp50="
  [mod."github.com/vektah/gqlparser/v2"]
    version = "v2.4.1"
    hash = "sha256-c90TTufmfLAsm0h+aWcOe4btEJmI/lg1kfar5ewVf/c="
  [mod."github.com/vektra/mockery/v2"]
    version = "v2.10.0"
    hash = "sha256-n2g8zkLJHSVmXKQsfWA3xqN+GAbHmt+7UkvImJXwo0k="
  [mod."github.com/xWTF/chardet"]
    version = "v0.0.0-20230208095535-c780f2ac244e"
    hash = "sha256-K36nDR/YMFvDMly0/ohGaq2c+ChEHSgO8Iww6Sxv5+8="
  [mod."go.uber.org/atomic"]
    version = "v1.7.0"
    hash = "sha256-g83RSzO/5k8W3qyiIsrQbVq1F8qJGccdWEXTjkqUOfc="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20220321153916-2c7772ba3064"
    hash = "sha256-rbakbSQ3FXJR+JkbTkhk1D86MUNswfEDtXsQvnhUnS4="
  [mod."golang.org/x/image"]
    version = "v0.0.0-20210220032944-ac19c3e999fb"
    hash = "sha256-V3hwNVeqOvBVR1mp7p8+xAlh8TwOrJDaCXM0hgOZjcY="
  [mod."golang.org/x/mod"]
    version = "v0.6.0-dev.0.20220419223038-86c51ed26bb4"
    hash = "sha256-HS5GtzK6mLkQ/FM+GWoX4wSW0XllHK/2O3Y7O2/sFBk="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20220722155237-a158d28d115b"
    hash = "sha256-TccMT2GgC1qKp8Yxk1zShJVvr29GemCqKSNJeYkjLo4="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20220808155132-1c4a2a72c664"
    hash = "sha256-t9g2ocz2fznpSd6iS1hToXHfLgblUHmRab/kCyailMo="
  [mod."golang.org/x/term"]
    version = "v0.0.0-20210927222741-03fcf44c2211"
    hash = "sha256-DsX2xay7Y/0/bikp4vU8ArF0B6KHyqEc37PwgvmjhSs="
  [mod."golang.org/x/text"]
    version = "v0.3.7"
    hash = "sha256-XH2pUzzQx95O0rak00grQvfACfL+EmZiV7ZzJBkX+XY="
  [mod."golang.org/x/tools"]
    version = "v0.1.12"
    hash = "sha256-D0kGneGMt+LFbdUDo9Axd0yB0a5t3Z0YKVAnJDDaBo8="
  [mod."gopkg.in/guregu/null.v4"]
    version = "v4.0.0"
    hash = "sha256-VhFHFjDVv5mnyLGefthH2ViaPsPab4NOSSW7XqzBpfI="
  [mod."gopkg.in/ini.v1"]
    version = "v1.66.4"
    hash = "sha256-PZ5vwf47Pjv7lzaUlm/mIdkIfnwEpmSNYG1UIfGh3M4="
  [mod."gopkg.in/sourcemap.v1"]
    version = "v1.0.5"
    hash = "sha256-RCth4NlsGFI+G8JSIZKDLvmrtbWgMoHdqHbBEWgTLiM="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.0-20210107192922-496545a6307b"
    hash = "sha256-j8yDji+vqsitpRZirpb4w/Em8nstgf28wpwkcrOlxBk="
